* =consult-org-roam= -- An Unofficial Extension
This is a small collection of functions to operate [[https://github.com/org-roam/org-roam][org-roam]] with the
help of [[https://github.com/minad/consult][consult]] and its live preview feature.

* Overview and usage
=consult-org-roam.el= provides several functions to connect org-roam
to consult's completing read interface. On the one hand, it provides
the following standalone functions which enhance =org-roam='s
capabilities:

- =consult-org-roam-rg-search= :: Search your roam-directory with grep
  or [[https://github.com/BurntSushi/ripgrep][ripgrep]]
- =consult-org-roam-backlinks= :: List backlinks to
  =org-roam-node-at-point= (e.g. currently open note) and sift through
  them with consult's completing-read and its live preview
- =consult-org-roam-file-find= :: Search your org-roam files with
  consult's completing-read and its live preview

On the other hand, it provides a minormode called
=consult-org-roam-mode=. When activated =org-roam-node-read= is
overridden which is used by =org-roam-node-find=,
=org-roam-node-insert= and =org-roam-refile=. By doing so, all
functions utilizing completing-read resort to =consult= for performing
completion. Furthermore, the same is done for =org-roam-ref-read= so
that =consult= is used for completing references as well.

Eventually, you might want to suppress previewing for certain
functions. This can be done by adding the above mentioned functions to
=consult-org-roam-no-preview-functions=.

* Installation

#+begin_src elisp
(use-package consult-org-roam
   :straight (:host github :repo "jgru/consult-org-roam")
   :init
   (require 'consult-org-roam)
   ;; Activate the minor-mode
   (consult-org-roam-mode 1)
   :custom
   (consult-org-roam-grep-func #'consult-ripgrep)
   ;; Eventually suppress previewing for certain functions
   ;;(consult-org-roam-no-preview-functions '(consult-org-roam-forward-links consult-org-roam-backlinks))
   :bind
   ("C-c n e" . consult-org-roam-file-find)
   ("C-c n b" . consult-org-roam-backlinks)
   ("C-c n r" . consult-org-roam-search))
#+end_src

* Dependencies
=consult-org-roam= is built on top of [[https://github.com/org-roam/org-roam][org-roam]] and [[https://github.com/minad/consult][consult]], it relies on its functionality.

Furthermore, ensure that you have [[https://github.com/BurntSushi/ripgrep][ripgrep]] installed on your system, if
you set =consult-org-roam-grep-func= to =#'consult-ripgrep=.
